### ISSUE TITLE
why the probability is 1/14？

### ISSUE THREAD

**Issue by DongBeiDaMao** [jayluxferro/IoT-IDS#7]
Hello , I have some questions about the paper.
1. why the probability is 1/14？Is it because there are 14 params to compare?
2. If the method to differ real AP from rogue AP is to find whether the 14 params were totally same , then why not just count the number of same params? Instead , the Eq. H(S)=−plog2p is used in the paper.

**Comment by jayluxferro** [comment]
Hi @DongBeiDaMao , in the base implementation there were 14 params to compare. It's not always the case you might decide to assign the same probability to each characteristics; depending on how useful it is and also what exact characteristics you are considering. That was the basis for using the Entropy equation although in the base implementation a simple summation would have suffice.

**Comment by DongBeiDaMao** [comment]
I understand it now! Thank you for your answer.
